# Generated by Django 5.1.6 on 2025-02-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('imagen', models.ImageField(upload_to='peliculas/')),
                ('trailer_url', models.URLField()),
                ('estreno', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='estrenos',
        ),
    ]
