# Generated by Django 5.1.6 on 2025-02-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_pelicula_delete_estrenos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='trailer_url',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='descripcion',
            field=models.TextField(default='Sin descripción'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='duracion',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='estreno',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas/'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
