# Generated by Django 5.1.6 on 2025-02-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_pelicula_trailer_url_pelicula_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
