# Generated by Django 5.1.6 on 2025-02-25 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_pelicula_trailer_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
