# Generated by Django 5.1.6 on 2025-02-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0005_delete_pelicula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('trailer_url', models.URLField(help_text='URL de YouTube (formato embed)')),
                ('imagen', models.ImageField(upload_to='peliculas/')),
                ('categoria', models.CharField(choices=[('Romance y Drama', 'Romance y Drama'), ('Ciencia ficción y fantasía', 'Ciencia ficción y fantasía'), ('Acción', 'Acción'), ('Comedia', 'Comedia'), ('Terror', 'Terror'), ('Documentales', 'Documentales')], max_length=50)),
                ('calificacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha_estreno', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
            },
        ),
    ]
