# Generated by Django 5.1.6 on 2025-02-26 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='trailer_url',
            field=models.URLField(help_text='URL de YouTube (se convertirá automáticamente a formato embed)'),
        ),
    ]
