# Generated by Django 5.1.6 on 2025-02-28 11:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_reservas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
    ]
