# Generated by Django 5.1.6 on 2025-03-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_orden_ordenitem_delete_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ordenitem',
            name='producto',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='horario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenItem',
        ),
    ]
