# Generated by Django 5.1.6 on 2025-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_producto_remove_reserva_productos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cantidad_personas',
            field=models.IntegerField(default=1),
        ),
    ]
