# Generated by Django 5.1.6 on 2025-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_reserva_cantidad_personas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='productos',
            field=models.ManyToManyField(blank=True, to='cinema.producto'),
        ),
    ]
