# Generated by Django 5.1.6 on 2025-03-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_datos'),
        ('cinema', '0017_reserva_productos'),
    ]

    operations = [
    ]
