# Generated by Django 5.1.6 on 2025-03-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_merge_0016_datos_0017_reserva_productos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='carrito',
        ),
        migrations.RemoveField(
            model_name='itemcarrito',
            name='producto',
        ),
        migrations.AlterModelOptions(
            name='pelicula',
            options={'ordering': ['orden'], 'verbose_name': 'Película', 'verbose_name_plural': 'Películas'},
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='cantidad_personas',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='personas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='productos',
            field=models.ManyToManyField(blank=True, to='cinema.pelicula'),
        ),
        migrations.DeleteModel(
            name='Carrito',
        ),
        migrations.DeleteModel(
            name='ItemCarrito',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
