# Generated by Django 5.1.6 on 2025-03-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0023_alter_estrenos_imagen'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='estrenos',
            new_name='Estreno',
        ),
        migrations.AlterModelOptions(
            name='estreno',
            options={'ordering': ['orden'], 'verbose_name': 'Estreno', 'verbose_name_plural': 'Estrenos'},
        ),
    ]
