# Generated by Django 5.1.6 on 2025-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0025_estrenos_delete_estreno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
