# Generated by Django 5.1.6 on 2025-03-11 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0027_estrenopelicula_delete_estrenos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContenidoCine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sinopsis', models.TextField()),
                ('video_promocional', models.URLField(help_text='URL de YouTube (se convertirá automáticamente a formato embed)')),
                ('imagen_portada', models.ImageField(upload_to='contenidos/')),
                ('genero', models.CharField(choices=[('Romance y Drama', 'Romance y Drama'), ('Ciencia ficción y fantasía', 'Ciencia ficción y fantasía'), ('Acción', 'Acción'), ('Comedia', 'Comedia'), ('Terror', 'Terror'), ('Documentales', 'Documentales')], max_length=50)),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha_lanzamiento', models.DateField(blank=True, null=True)),
                ('horarios_disponibles', models.CharField(blank=True, max_length=255, null=True)),
                ('prioridad', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Contenido de Cine',
                'verbose_name_plural': 'Contenidos de Cine',
                'ordering': ['prioridad'],
            },
        ),
    ]
