# Generated by Django 5.1.6 on 2025-03-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0031_historial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidocine',
            name='horarios_disponibles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenidocine',
            name='puntuacion',
            field=models.FloatField(choices=[(0.5, '0.5'), (1.0, '1.0'), (1.5, '1.5'), (2.0, '2.0'), (2.5, '2.5'), (3.0, '3.0'), (3.5, '3.5'), (4.0, '4.0'), (4.5, '4.5'), (5.0, '5.0')]),
        ),
    ]
