# Generated by Django 5.1.6 on 2025-03-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0032_alter_contenidocine_horarios_disponibles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidocine',
            name='horarios_disponibles',
        ),
        migrations.AddField(
            model_name='contenidocine',
            name='fecha_estreno',
            field=models.DateField(blank=True, null=True),
        ),
    ]
