# Generated by Django 5.1.6 on 2025-04-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0033_remove_contenidocine_horarios_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidocine',
            name='formato',
            field=models.CharField(choices=[('2D', '2D'), ('3D', '3D'), ('2D/3D', 'Disponible en ambos formatos')], default='2D', max_length=5, verbose_name='Formato de proyección'),
        ),
        migrations.AddField(
            model_name='contenidocine',
            name='funcion_2d',
            field=models.BooleanField(default=False, verbose_name='Disponible en 2D'),
        ),
        migrations.AddField(
            model_name='contenidocine',
            name='funcion_3d',
            field=models.BooleanField(default=False, verbose_name='Disponible en 3D'),
        ),
    ]
